Prezado(a) Aluno(a),

A presente tarefa tem como objetivo realizar o pré-processamento do conjunto de dados "Churn_Modelling_2.csv" de modo que ele fique perfeitamente adequado para aplicarmos um dos modelos de Aprendizado de Máquina que estudaremos adiante.

O conjunto de dados "Churn_Modelling_2.csv" contém detalhes dos clientes de um banco com uma variável de destino binária ("Exited") que reflete o fato de o cliente ter deixado o banco (encerrado sua conta) ou não.

Você deve construir um notebook para realizar os procedimentos abaixo sobre o conjunto de dados em questão. Tais procedimentos abordam a leitura do arquivo disponível no repositório GitHub da disciplina, seleção de variáveis, codificação de variáveis categóricas (strings), escalonamento de dados e separação de conjuntos de dados de treino e de teste.

Abra um novo notebook e implemente os seguintes passos:

1. Faça a leitura do arquivo "Churn_Modelling_2.csvLinks to an external site." disponível na pasta "ChurnLinks to an external site." no repositório GitHub da disciplinaLinks to an external site. e armazene numa variável como um dataframe;

In [ ]:
# Clonagem do repositório
!git clone 'https://github.com/malegopc/DSBD'

fatal: destination path 'DSBD' already exists and is not an empty directory.

In [ ]:
#importante bibliotecas
import pandas as pd

df = pd.read_csv('/content/DSBD/Datasets/Churn/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

2. Elimine instâncias (linhas) com dados ausentes para a variável "IsActiveMember".

In [ ]:
df = df.dropna(subset=['IsActiveMember'])
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Conferindo se os valores vazios foram eliminados
count_null_values = df['IsActiveMember'].isnull().sum()
print(f'O total de valores vazios na coluna IsActiveMember é {count_null_values}!')

O total de valores vazios na coluna IsActiveMember é 0!

3. Faça a imputação dos dados ausentes para a variável "NumOfProducts" utilizando a média da variável.

In [ ]:
# Calculando a média da variável "NumOfProducts"
NumOfProducts_mean = df['NumOfProducts'].mean()

# Preenchendo os dados ausentes
df['NumOfProducts'].fillna(NumOfProducts_mean, inplace=True)

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Conferindo se os valores ausentes foram preenchidos
count_null_values = df['NumOfProducts'].isnull().sum()
print(f'O total de valores vazios na coluna NumOfProducts é {count_null_values}!')

O total de valores vazios na coluna NumOfProducts é 0!

4. Crie uma variável (array) X que contenha os valores apenas dos atributos/colunas de "CreditScore" a "EstimatedSalary" utilizando a função "iloc" do Pandas. Em outras palavras, crie uma variável X que receba o dataframe inteiro exceto as 3 primeiras colunas e a última. Observe que as 3 primeiras colunas "RowNumber", "CustomerId" e "Surname" não são importantes e devem ser descartadas. E a última coluna ("Exited") será a variável destino ("target" ou saída) que será criada no próximo passo;

In [ ]:
# Excluindo as três primeiras coluna e a última
x = df.iloc[:, 3:-1]
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

5. Crie uma variável (array) y que contenha apenas a última coluna  ("Exited"). Esta é a variável destino ("target" ou saída);

In [ ]:
# Variável y com apenas a última coluna
y = df.iloc[:, -1]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

6. Codifique a coluna da variável X correspondente a variável categórica "Gender" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

x['Gender'] = encoder.fit_transform(x['Gender'])

x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64
9996,516,France,1,35,10,57369.61,1,1,1,101699.77
9997,709,France,0,36,7,0.00,1,0,1,42085.58
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52
9999,792,France,0,28,4,130142.79,1,1,0,38190.78

7. Codifique a coluna da variável X correspondente a variável categórica "Geography" como numérica por meio de Codificação de Variável Fictícia (Dummy Variable Encoding). Observe que há 3 países (categorias) diferentes. Atenção: esse talvez seja o passo mais difícil da tarefa. Você deve transformar o resultado da variável/coluna "Geography" para o formato binário (one-hot) de modo que fique representado por apenas duas colunas (de 0s e 1s). Além disso, essas duas novas colunas devem permanecer na mesma variável X. Dica: verifique a utilização da função make_column_transformerLinks to an external site. da biblioteca scikit-learn. Alternativamente, você pode utilizar a função pandas.get_dummiesLinks to an external site..

In [ ]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder


# Criando o objeto OneHotEncoder
onehot_encoder = OneHotEncoder(drop='first', sparse=False)

column_transformer = make_column_transformer((onehot_encoder, ['Geography']), remainder='passthrough')
x = pd.DataFrame(column_transformer.fit_transform(x), columns=['Geography_Spain', 'Geography_Germany'] + list(x.columns[1:]))

x = x.drop(['Geography'], axis=1)

x

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,Geography_Spain,Geography_Germany,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0.0,0.0,0.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88
1,0.0,1.0,0.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58
2,0.0,0.0,0.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57
3,0.0,0.0,0.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63
4,0.0,1.0,0.0,43.0,2.0,125510.82,1.0,1.0,1.0,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.0,1.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64
9996,0.0,0.0,1.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77
9997,0.0,0.0,0.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58
9998,1.0,0.0,1.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52
9999,0.0,0.0,0.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78

8. Divida as variáveis X e y em dados de treino e de teste utilizando o método "train_test_split", gerando as variáveis X_train, X_test, y_train e y_test. Você define a proporção de dados de treino e de teste;

In [ ]:
from sklearn.model_selection import train_test_split

test_size = 0.2

# Divide os dados em conjuntos de treino e teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, random_state=42)

x_train
x_test

y_train
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

9. Faça a padronização (escalonamento) dos dados das variáveis X_train e X_test utilizando a classe StandardScaler do scikit-learn;

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


# Printando o resultado
x_train_scaled
x_test_scaled

array([[ 1.72572313, -0.57638802,  0.91324755, ..., -1.54035103,
        -1.02583358, -1.01960511],
       [-0.57946723, -0.57638802,  0.91324755, ...,  0.64920267,
         0.97481699,  0.79888291],
       [-0.57946723,  1.73494238, -1.09499335, ...,  0.64920267,
        -1.02583358, -0.72797953],
       ...,
       [-0.57946723, -0.57638802, -1.09499335, ...,  0.64920267,
        -1.02583358, -1.16591585],
       [-0.57946723, -0.57638802,  0.91324755, ...,  0.64920267,
        -1.02583358, -0.41163463],
       [ 1.72572313, -0.57638802,  0.91324755, ...,  0.64920267,
         0.97481699,  0.12593183]])

1-) Você deve aplicar os seguintes algoritmos de AM:

Regressão Logística

KNN - K-Nearest Neighbors (k-vizinhos mais próximos)

SVM - Support Vector Machines (Máquinas de Vetores de Suporte )

Random Forest

In [ ]:
# Mostrando os dados do dataset original
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Regressão Logística

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Regressão Logística
model = LogisticRegression(random_state=42)
model.fit(x_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)

# Avaliar o desempenho do modelo
model_result = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'O desempenho do modelo após a aplicação do modelo de regressão logística é: {model_result}\n')
print(f'Matriz de Confusão:\n{conf_matrix}\n')
print(f'Relatório de Classificação:\n{class_report}')

O desempenho do modelo após a aplicação do modelo de regressão logística é: 0.8012

Matriz de Confusão:
[[2003    0]
 [ 497    0]]

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      2003
           1       0.00      0.00      0.00       497

    accuracy                           0.80      2500
   macro avg       0.40      0.50      0.44      2500
weighted avg       0.64      0.80      0.71      2500

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

KNN - K-Nearest Neighbors (k-vizinhos mais próximos)

In [ ]:
# KNN - K-Nearest Neighbors (k-vizinhos mais próximos)
from sklearn.neighbors import KNeighborsClassifier

# Criar e treinar o modelo KNN
k = 3
model = KNeighborsClassifier(n_neighbors=k)
model.fit(x_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)

# Avaliar o desempenho do modelo
model_result_KNN = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'O desempenho do modelo após a aplicação do modelo KNN é: {model_result_KNN}\n')
print(f'Matriz de Confusão:\n{conf_matrix}\n')
print(f'Relatório de Classificação:\n{class_report}')

O desempenho do modelo após a aplicação do modelo KNN é: 0.7376

Matriz de Confusão:
[[1788  215]
 [ 441   56]]

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.80      0.89      0.84      2003
           1       0.21      0.11      0.15       497

    accuracy                           0.74      2500
   macro avg       0.50      0.50      0.50      2500
weighted avg       0.68      0.74      0.71      2500

SVM - Support Vector Machines (Máquinas de Vetores de Suporte)

In [ ]:
# SVM - Support Vector Machines (Máquinas de Vetores de Suporte)
from sklearn.svm import SVC

# Criar e treinar o modelo SVM
model = SVC(kernel='linear', random_state=42)
model.fit(x_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)

# Avaliar o desempenho do modelo
model_result_SVM = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'O desempenho do modelo após a aplicação do modelo SVM é: {model_result_SVM}')
print(f'Matriz de Confusão:\n{conf_matrix}')
print(f'Relatório de Classificação:\n{class_report}')

O desempenho do modelo após a aplicação do modelo SVM é: 0.7864
Matriz de Confusão:
[[1939   64]
 [ 470   27]]
Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.80      0.97      0.88      2003
           1       0.30      0.05      0.09       497

    accuracy                           0.79      2500
   macro avg       0.55      0.51      0.49      2500
weighted avg       0.70      0.79      0.72      2500

Random Forest

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

# Criar e treinar o modelo Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)

# Avaliar o desempenho do modelo
model_result_forest = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'O desempenho do modelo após a aplicação do modelo Random Forest é: {model_result_forest}')
print(f'Matriz de Confusão:\n{conf_matrix}')
print(f'Relatório de Classificação:\n{class_report}')

O desempenho do modelo após a aplicação do modelo Random Forest é: 0.8612
Matriz de Confusão:
[[1917   86]
 [ 261  236]]
Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2003
           1       0.73      0.47      0.58       497

    accuracy                           0.86      2500
   macro avg       0.81      0.72      0.75      2500
weighted avg       0.85      0.86      0.85      2500